---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont-1
          image: shaikali0223/app:v1
          ports:
            - containerPort: 8080




---
apiVersion: v1
kind: Service
metadata:
  name: appsvc
spec:
  type: LoadBalancer
  selector:
    app: swiggy
  ports:
    - port: 8080
      targetPort: 8080
